- name: 01 patch LuaJIT to embed redis.parser
  lineinfile:
    path: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src/lib_init.c"
    insertafter: '#include "lj_arch.h"'
    line: |

      LUALIB_API int luaopen_redis_parser(lua_State *l);

- name: 02 patch LuaJIT to embed redis.parser
  lineinfile:
    path: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src/lib_init.c"
    insertafter: 'static const luaL_Reg lj_lib_preload'
    line: |-
      { "redis.parser",		luaopen_redis_parser },

- name: register redis-parser directory name
  shell: "echo lua-redis-parser-*"
  register: _redis_parser_dir
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/"

- name: build redis_parser.o
  command: >
    make redis-parser.o
  environment:
    LUA_INCLUDE_DIR: "{{ openresty_version_build_path }}/bundle/{{ _luajit_dir.stdout }}/src"
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/{{ _redis_parser_dir.stdout }}"

- name: create libredisparser.a
  command: >
    ar rcus {{ openresty_build_path }}/libredisparser.a redis-parser.o
  args:
    chdir: "{{ openresty_version_build_path }}/bundle/{{ _redis_parser_dir.stdout }}"

- name: add redisparser to TARGET_LIBS
  set_fact:
    _luajit_target_libs: "{{ _luajit_target_libs|default('') }} -L{{ openresty_build_path }} -lredisparser"
    _ngx_ld_opt: "{{ _ngx_ld_opt|default('') }} -lredisparser"
